---
title: "CMIP_contributions"
author: "Denisse Fierro Arcos"
date: "2024-01-10"
output:
  github_document:
    toc: true
    html_preview: false
---

# Map comparing regional models by CMIP version

## Loading libraries

```{r}
#Manipulating data
library(dplyr)
library(stringr)
library(fuzzyjoin)
#Spatial data
library(sf)
#Base map
library(rnaturalearth)
#Plotting maps
library(ggplot2)
library(cowplot)
library(RColorBrewer)
```

## Loading FishMIP regional models shapefile

```{r}
#Creating data frame with regional models to be included
cmip_model <- tibble(region = c("Baltic Sea", "Humboldt", "Mediterranean", "North Sea", "SE Australia",
                                "Benguela", "East Bering", "Hawaii",
                                "Cook Strait", "East Bass"),
                     #CMIP version used
                     esm = c(rep("CMIP5", 5), rep("CMIP6", 3), rep("CMIP5 & CMIP6", 2))) |> 
  mutate(esm = factor(esm, ordered = T, levels = c("CMIP5", "CMIP6", "CMIP5 & CMIP6")))

#Selecting regional models based on data frame above
cmip_comp <- read_sf("../Outputs/FishMIP_regional_models/FishMIP_regional_models.shp") |> 
  #Partial match of region name
  fuzzy_inner_join(cmip_model, by = "region", match_fun = str_detect) |> 
  #Remove second "region" column because it does not contain full names
  select(!region.y) |> 
  #Rename original "region" column
  rename("region" = "region.x")

#Checking results
cmip_comp
```
  
### Data preparation  
We will use a Robinson projection for our map, so we need to reproject our shapefile. A reprojection also needs to be applied to our base world map.  
  
```{r}
#Define Robinson projection to be applied to shapefile and basemap
rob_proj <- "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs"

#Load world base map
world <- ne_countries(scale = "medium", returnclass = "sf") |> 
  #Ensuring any polygons crossing international dateline are correctly plotted
  st_wrap_dateline() |> 
  #Reprojecting
  st_transform(rob_proj)

#Reprojecting FishMIP regions
cmip_comp_rob <- cmip_comp |> 
  st_wrap_dateline() |> 
  st_transform(rob_proj)
```
  
## Plotting map 
  
```{r}
#Plotting 
reg <- cmip_comp_rob |> 
  #Plotting
  ggplot()+
  #Color regions by CMIP version used
  geom_sf(aes(fill = esm), alpha = 0.5, linewidth = 0.65)+
  geom_sf(data = world, fill = "#f9f9f5", show.legend = F)+
  #Selecting colourblind friendly colours
  scale_fill_manual(values = c("#ddaa33", "#bb5566", "#004488"))+
  theme_bw()+
  #Move legend to bottom
  theme(legend.position = "bottom", legend.title = element_blank(),
        legend.margin = margin(0, 0, 0, 0),
        legend.box.margin = margin(0, 0, 0, 0),
        legend.text = element_text(margin = margin(r = 5)),
        panel.border = element_rect(colour = NA))+
  #Split legend into four columns
  guides(fill = guide_legend(nrow = 1))

#Checking map so far
reg
```
  
### Saving map to disk
  
```{r}
#Saving final map
ggsave("../Outputs/FishMIP_regional_models_cmip_comparison.pdf", reg, device = "pdf", 
       width = 18.75, height = 15, units = "cm")
```